# codecov.yml
coverage:
  status:
    project:
      default:
        # basic
        target: 80%
        threshold: 2%
        base: auto
        paths: 
          - "promptsmith"
        # advanced settings
        if_ci_failed: error
        informational: false
        only_pulls: false

    patch:
      default:
        # basic
        target: 80%
        threshold: 2%
        base: auto
        # advanced settings
        if_ci_failed: error
        informational: false
        only_pulls: false

ignore:
  - "tests/"
  - "setup.py"